[gcp_service_account]
type = "service_account"
project_id = "oracle-v3"
private_key_id = "b1d0c2b27259785b2511941aab7da97801e5128d"
client_email = "oracle-bot@oracle-v3.iam.gserviceaccount.com"
client_id = "116577828194789498863"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/oracle-bot%40oracle-v3.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDhuV4hE9nVnCph
OvCpjxBBefARpiaBwnUP2PItD6660P3FNKVf19Q05Ao42fg346YWn+hhnMDwPtwp
rFNdbtpaSK4LPVDnQgk2yDe43nEMzmP4rQ1FTgkbm2t2eb/xIhG+6as7oAzQHqHT
Va1GNZJa4yFwuJs4dCh7Le2ES4t5F0nC0zt31zwzZvMa9gdNIeFu4bGfz8MZlslH
PezvV3KJWgPGvQQqwFwK9ocEcPpXvulfFkS4EjvZ0KaPr3ZBF+2N5bk+ARd37zCi
T4KWNUMZ98ByVjDrGehtCPKlMsnvrwOOT58lC4CAKYXLmapGTtj5YYqiyXT3Nz6
u9oufEgdAgMBAAECggEACBjabyTTZwXRq7MN0C31Mb1s9sZx8gHWqaweWdlKwGGq
rMY78Bwhp7O4yHvMhegOZ0LdYZJaMHQMzpjjf6ya5sCzL5eHkq121PvUgIxIMWL+
STzJ8anANWOQn2DJhB31ACxz1kZ3lzKgxaA4lZYVNdnucz5IC9EiOkhLkXfqnPwU
h+XxsmNlx56DjKWiKviYXaiMgSb9+TUee8w1T/xeiSZBbmMIp4tmgA0sNeGxVsAc
t7oiUSnJV2YluyUt8/pBWYoZ04eAbfsTRzHGl4OlEzpiio774e32UUnpLd3kdP/N
RClECJ08rQ/KWLQ4Yu0EtwN6bxe2kx4CvmAppJPzWQKBgQD68ukthD0XZDAyoDe1
5UPv4EwNoi3Yxy5ubDUxfRyUcsgmtDu/mv2cyqlPLLf8VyplBcfs89Bb9boFAI6s
yjIVcM7Bw+ce38mQANz9DkQPv5efTHNF2XEMB8BVmKJXCWslBfTUbJd8eVEyaFwc
7+DlTCJlRvzJFu0rhhjIkqSWGQKBgQDmRHqHJn2WFZKV2SS3ZDVihAEASJHimuJs
DT2NQ2LIpvem+RBfJvHPvqdodTGFx9648aDOjjB8xLgbNPSn+w3PD78c+gZf6w9W
70hGpk6Mj1RUn+PVBLM0xZfo4/m0Ztlz8cTS+fhcT2uFc4opzT+r2ilr8fpB9/l/
694dR5EapQKBgFHzZcaherna1AqUW90g49DANNX28nXqhfU1jSF+NAkeetJ45VHX
l57OaAAdIHBdntCi1KlC7fY6Bud/SRiQZ06tKjgI278vYcmPHpvdPsjNzpwNAU/8
NHizR1IsqEc4Ii9TBKMiW04g6C1H+1zP0WfQNyNPzVl2DTm7bviBOxJxAoGBANSC
kF4YfMC9agoXW5ZQyiAAWXgsgU6TyLEVyx+K+CjcRyR3Kc/W/kXO22tA9RJVMkyW
2uSmP0N2vb6GMeCxhr3491TDvoxZQE/oB1kEdOut/5MV+MsISmdCkH7jnvkKDle9
4fsfrUFsHnwL9I+9l6x/a8juihrFwyJ2yQdWnCjtAoGAHWiil0RCT/vwm6IPGPso
/oCNCLDNQBBm3qrPgBwZnC4/3v6EMeOjOoWqU3ypYPJfHS/HhbBMby1xyabAb6xZ
NgCy+XjIxLWIsqAFxNLZjItsijmmcS1pGLBssxega+wJ/a/mZ9KRkyjg3u4QDnwO
ElunpdfcPtFtro3eMBM/zNE=
-----END PRIVATE KEY-----
"""
